# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0002_auto_20171114_1802'),
        ('topic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChosenByEditorsAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChosenByEditorsByTopicAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Answer')),
                ('following_topics', models.ManyToManyField(related_name='answer_chosen_by_editors_by_topic_admins', to='topic.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChosenByEditors',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Answer')),
            ],
            bases=('feed.activity',),
        ),
        migrations.CreateModel(
            name='AnswerChosenByEditorsByTopic',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Answer')),
                ('following_topics', models.ManyToManyField(related_name='_answerchosenbyeditorsbytopic_following_topics_+', to='topic.Topic')),
            ],
            bases=('feed.activity',),
        ),
        migrations.CreateModel(
            name='AnswerLikedByFollowingUser',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Answer')),
                ('following_users', models.ManyToManyField(related_name='_answerlikedbyfollowinguser_following_users_+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('feed.activity',),
        ),
        migrations.CreateModel(
            name='AnswerWroteByFollowingUser',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Answer')),
                ('following_users', models.ManyToManyField(related_name='_answerwrotebyfollowinguser_following_users_+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('feed.activity',),
        ),
        migrations.CreateModel(
            name='AnswerWroteOnFollowingTopic',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Answer')),
                ('following_topics', models.ManyToManyField(related_name='_answerwroteonfollowingtopic_following_topics_+', to='topic.Topic')),
            ],
            bases=('feed.activity',),
        ),
        migrations.CreateModel(
            name='QuestionFollowedByFollowingUser',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('following_users', models.ManyToManyField(related_name='_questionfollowedbyfollowinguser_following_users_+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Question')),
            ],
            bases=('feed.activity',),
        ),
        migrations.CreateModel(
            name='QuestionWroteByFollowingUser',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('following_users', models.ManyToManyField(related_name='_questionwrotebyfollowinguser_following_users_+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Question')),
            ],
            bases=('feed.activity',),
        ),
        migrations.CreateModel(
            name='QuestionWroteOnFollowingTopic',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.Activity')),
                ('following_topics', models.ManyToManyField(related_name='_questionwroteonfollowingtopic_following_topics_+', to='topic.Topic')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contents.Question')),
            ],
            bases=('feed.activity',),
        ),
        migrations.AddField(
            model_name='activity',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
