# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchosenbyeditorsbytopicadmin',
            name='following_topics',
        ),
        migrations.AddField(
            model_name='answerchosenbyeditorsbytopicadmin',
            name='topics',
            field=models.ManyToManyField(help_text='이 토픽들의 팔로워들에게 activity들이 자동으로 생성됩니다. 추가하지 않아도 자동으로 answer의 topic들이 추가되지만, 추가적으로 명시할 수 있습니다.', related_name='answer_chosen_by_editors_by_topic_admins', to='topic.Topic'),
        ),
    ]
