# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('sample_image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
