# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='sample_image',
            new_name='topic_image',
        ),
    ]
