export const GET_QUESTIONS_REQUEST = 'app/ProfilePage/GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'app/ProfilePage/GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'app/ProfilePage/GET_QUESTIONS_FAILURE';

export const GET_FOLLOWING_TOPICS_REQUEST = 'app/ProfilePage/GET_FOLLOWING_TOPICS_REQUEST';
export const GET_FOLLOWING_TOPICS_SUCCESS = 'app/ProfilePage/GET_FOLLOWING_TOPICS_SUCCESS';
export const GET_FOLLOWING_TOPICS_FAILURE = 'app/ProfilePage/GET_FOLLOWING_TOPICS_FAILURE';

export const GET_FOLLOWERS_REQUEST = 'app/ProfilePage/GET_FOLLOWERS_REQUEST';
export const GET_FOLLOWERS_SUCCESS = 'app/ProfilePage/GET_FOLLOWERS_SUCCESS';
export const GET_FOLLOWERS_FAILURE = 'app/ProfilePage/GET_FOLLOWERS_FAILURE';

export const GET_FOLLOWING_USERS_REQUEST = 'app/ProfilePage/GET_FOLLOWING_USERS_REQUEST';
export const GET_FOLLOWING_USERS_SUCCESS = 'app/ProfilePage/GET_FOLLOWING_USERS_SUCCESS';
export const GET_FOLLOWING_USERS_FAILURE = 'app/ProfilePage/GET_FOLLOWING_USERS_FAILURE';

export const CHANGE_ACTIVE_ITEM = 'app/ProfilePage/CHANGE_ACTIVE_ITEM';

export const OPEN_CREDENTIAL_FORM_MODAL = 'app/ProfilePage/OPEN_CREDENTIAL_FORM_MODAL';
export const CLOSE_CREDENTIAL_FORM_MODAL = 'app/ProfilePage/CLOSE_CREDENTIAL_FORM_MODAL';

export const GET_PROFILE_REQUEST = 'app/ProfilePage/GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'app/ProfilePage/GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'app/ProfilePage/GET_PROFILE_FAILURE';

export const FOLLOW_TOPIC_REQUEST = 'app/ProfilePage/FOLLOW_TOPIC_REQUEST';
export const FOLLOW_TOPIC_SUCCESS = 'app/ProfilePage/FOLLOW_TOPIC_SUCCESS';
export const FOLLOW_TOPIC_FAILURE = 'app/ProfilePage/FOLLOW_TOPIC_FAILURE';

export const INITIALIZE_STATE = 'app/ProfilePage/INITIALIZE_STATE';
