# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171107_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='followers', to='topic.Topic'),
        ),
    ]
