# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171114_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='left_invite_keys',
        ),
    ]
