# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_left_invite_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': '해당 이메일로 가입된 계정이 이미 있습니다.'}, max_length=254, null=True, unique=True),
        ),
    ]
