# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_answerer',
            field=models.BooleanField(default=True),
        ),
    ]
