export const CLEAR_FEED = 'app/HomePage/CLEAR_FEED';

export const GET_ACTIVITIES_REQUEST = 'app/HomePage/GET_ACTIVITIES_REQUEST';
export const GET_ACTIVITIES_SUCCESS = 'app/HomePage/GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_FAILURE = 'app/HomePage/GET_ACTIVITIES_FAILURE';

export const CHANGE_ACTIVE_CATEGORY = 'app/HomePage/CHANGE_ACTIVE_CATEGORY';
export const CHECK_ACTIVE_CATEGORY = 'app/HomePage/CHECK_ACTIVE_CATEGORY';
