export const CONNECT_NOTIFICATION_WEB_SOCKET_REQUEST = 'app/global/notification/CONNECT_NOTIFICATION_WEB_SOCKET_REQUEST';

export const GET_UNREAD_NOTIFICATION_COUNT_REQUEST = 'app/global/notification/GET_UNREAD_NOTIFICATION_COUNT_REQUEST';

export const GET_UNREAD_NOTIFICATION_COUNT_SUCCESS = 'app/global/notification/GET_UNREAD_NOTIFICATION_COUNT_SUCCESS';

export const GET_UNREAD_NOTIFICATION_COUNT_FAILURE = 'app/global/notification/GET_UNREAD_NOTIFICATION_COUNT_FAILURE';

export const GET_NOTIFICATIONS_REQUEST = 'app/global/notification/GET_NOTIFICATIONS_REQUEST';

export const GET_NOTIFICATIONS_SUCCESS = 'app/global/notification/GET_NOTIFICATIONS_SUCCESS';

export const GET_NOTIFICATIONS_FAILURE = 'app/global/notification/GET_NOTIFICATIONS_FAILURE';

export const UPDATE_NEW_NOTIFICATION = 'app/global/notification/UPDATE_NEW_NOTIFICATION';

export const UPDATE_LAST_NOTIFICATION_CHECK_REQUEST = 'app/global/notification/UPDATE_LAST_NOTIFICATION_CHECK_REQUEST';

export const READ_NOTIFICATION_REQUEST = 'app/global/notification/READ_NOTIFICATION_REQUEST';
