/*
 *
 * Global constants
 *
 */

export const AUTH_INVALID = 'app/global/AUTH_INVALID';

export const UPDATE_USER_INFO_REQUEST = 'app/global/UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'app/global/UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILURE = 'app/global/UPDATE_USER_INFO_FAILURE';

export const GET_FOLLOWING_TOPICS_REQUEST = 'app/global/GET_FOLLOWING_TOPICS_REQUEST';
export const GET_FOLLOWING_TOPICS_SUCCESS = 'app/global/GET_FOLLOWING_TOPICS_SUCCESS';

export const SHOW_TOAST_REQUEST = 'app/global/SHOW_TOAST_REQUEST';
export const SHOW_TOAST_SUCCESS = 'app/global/SHOW_TOAST_SUCCESS';

export const SEND_LOGIN_SIGNAL = 'app/global/SEND_LOGIN_SIGNAL';

export const S3_UPLOAD_SUCCESS = 'app/global/S3_UPLOAD_SUCCESS';
export const S3_UPLOAD_FAILURE = 'app/global/S3_UPLOAD_FAILURE';

export const GET_MAIN_SEARCH_REQUEST = 'app/global/GET_MAIN_SEARCH_REQUEST';
export const GET_MAIN_SEARCH_SUCCESS = 'app/global/GET_MAIN_SEARCH_SUCCESS';
export const GET_MAIN_SEARCH_FAILURE = 'app/global/GET_MAIN_SEARCH_FAILURE';

export const LOGOUT = 'app/global/LOGOUT';

export const UPDATE_REDIRECT_PAGE_REQUEST = 'app/global/UPDATE_REDIRECT_PAGE_REQUEST';

export const UPDATE_LOGGED_IN_USER = 'app/global/UPDATE_LOGGED_IN_USER';

export const OPEN_ANNOUNCE_MODAL_REQUEST = 'app/global/OPEN_ANNOUNCE_MODAL_REQUEST';
export const CLOSE_ANNOUNCE_MODAL_REQUEST = 'app/global/CLOSE_ANNOUNCE_MODAL_REQUEST';

export const STORE_ACCESS_TOKEN_REQUEST = 'app/global/STORE_ACCESS_TOKEN_REQUEST';
export const EMPTY_ACCESS_TOKEN_REQUEST = 'app/global/EMPTY_ACCESS_TOKEN_REQUEST';
