# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_auto_20171102_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowYouNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.Notification')),
                ('followers', models.ManyToManyField(related_name='follow_you_notification', to=settings.AUTH_USER_MODEL)),
                ('recent_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_you_notification_recent', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('notification.notification',),
        ),
    ]
