# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_followyounotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.Notification')),
                ('text', models.TextField()),
                ('image', models.URLField(blank=True, default='https://s3.ap-northeast-2.amazonaws.com/flova/assets/notification_default.jpg')),
                ('destination_path', models.TextField(blank=True, default='')),
            ],
            bases=('notification.notification',),
        ),
    ]
