# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_customnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationForAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.URLField(default='https://s3.ap-northeast-2.amazonaws.com/flova/assets/notification_default.jpg')),
                ('destination_path', models.TextField(blank=True, default='/')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationForFirstUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.URLField(default='https://s3.ap-northeast-2.amazonaws.com/flova/assets/notification_default.jpg')),
                ('destination_path', models.TextField(blank=True, default='/')),
            ],
        ),
        migrations.AlterField(
            model_name='customnotification',
            name='destination_path',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='customnotification',
            name='image',
            field=models.URLField(default='https://s3.ap-northeast-2.amazonaws.com/flova/assets/notification_default.jpg'),
        ),
    ]
