/**
 * Created by donghoon on 18. 1. 26.
 */
export const firstAnswererAnnounce = {
  title: '혹시 답변을 처음 작성하시나요?',
  content: '[{"key":"ypvdpvcj3","type":"unstyled","depth":0,"text":"가치있는 공간을 만들기 위해서 몇 가지 지켜주셨으면 하는 것들이 있습니다. 답변을 작성하기 전에 한 번만 읽어주세요 :)","styles":[],"entities":[]},{"key":"rj4epvcj","type":"unstyled","depth":0,"text":"","styles":[],"entities":[]},{"key":"xf5epvcj","type":"unordered-list-item","depth":0,"text":"답변에 최소한의 내용은 담아주세요!  답변을 읽는 사람들이 유의미한 정보를 얻어갈 수 있도록 최소한의 내용은 담아주세요. 물론 경우에 따라서는 짧아도 충분히 질문에 대한 답이 될 수도 있습니다. 하지만 그런 예외적인 상황들을 제외하고는 웬만하면 한 문장 내외로 이루어진 짧은 답변은 지양해주세요.","styles":[{"type":"bold","start":0,"length":21}],"entities":[]},{"key":"xukepvcj","type":"unordered-list-item","depth":1,"text":"외부 링크로 답변을 대체할 때에도 그 내용에 대한 간단한 요약이나 생각이라도 적어주세요. 해당 링크를 첨부한 간단한 이유를 적는 것도 괜찮습니다. (eg. 질문에 대한 좋은 답이 될 만한 글이 있어 링크로 첨부합니다.)","styles":[],"entities":[]},{"key":"z5sepvcj","type":"unordered-list-item","depth":0,"text":"다른 사람의 의견을 존중해주세요!  어떤 문제에 대해 다른 견해를 가진 사람도 있을 수 있습니다. 하지만, 다른 견해를 가졌다고 해서 비난하거나 조롱하기보다는 다른 견해를 존중하고 다르게 생각하는 부분에 대해 대화를 해보려고 노력한다면 어떨까요.","styles":[{"type":"bold","start":0,"length":20}],"entities":[]},{"key":"0l3fpvcj","type":"unstyled","depth":0,"text":"","styles":[],"entities":[]},{"key":"vk4fpvcj","type":"unstyled","depth":0,"text":"자세한 사항은 아래를 참고해주시기 바랍니다.","styles":[],"entities":[]},{"key":"zi9fpvcj","type":"unstyled","depth":0,"text":"Q. 플로바는 어떤 답변을 지향하나요?","styles":[],"entities":[{"type":"link","start":0,"length":21,"data":{"url":"https://flova.kr/question/84"}}]}]',
};

export const over50CharacterAnnounce = {
  title: '답변을 가이드라인에 맞게 작성해주세요!',
  content: '[{"key":"3xngyzcj","type":"unstyled","depth":0,"text":"현재 답변은 50자 이상 작성해주셔야 등록할 수 있습니다.","styles":[{"type":"bold","start":0,"length":32}],"entities":[]},{"key":"7whkyzcj78","type":"unstyled","depth":0,"text":"​","styles":[],"entities":[]},{"key":"7whkyzcj79","type":"unstyled","depth":0,"text":"저희가 이 서비스를 만들게 된 가장 큰 이유는 기존 Q&A 서비스들이 전반적으로 답변의 질이 떨어지고, 지식 공유의 공간으로서 제대로 된 역할을 하고 있지 못하고 있다는 문제의식 때문이었습니다.","styles":[],"entities":[]},{"key":"7whkyzcj80","type":"unstyled","depth":0,"text":"그러다보니 가치 있는 지식이 공유되는 공간을 만들어나가기 위해서는 어떻게 해야할지가 저희의 가장 큰 고민거리가 된 것은 어찌보면 당연합니다.","styles":[],"entities":[]},{"key":"7whkyzcj81","type":"unstyled","depth":0,"text":"​","styles":[],"entities":[]},{"key":"7whkyzcj82","type":"unstyled","depth":0,"text":"50자 이상이라는 기준은 답변의 질을 보장하기 위한 최소한의 기준입니다. 상황에 따라 다를 수 있다는 것을 감안해도 50자 이상은 지켜야 할 필요가 있다고 생각해서 그렇게 기준을 정하게 되었습니다.","styles":[],"entities":[]},{"key":"8whkyzcj","type":"unstyled","depth":0,"text":"​","styles":[],"entities":[]},{"key":"8whkyzcj83","type":"unstyled","depth":0,"text":"사람들이 답변을 읽었을 때 의미있는 정보를 얻어갈 수 있도록 답변에 충분한 내용을 작성해주시길 부탁드립니다.","styles":[],"entities":[]},{"key":"8whkyzcj84","type":"unstyled","depth":0,"text":"​","styles":[],"entities":[]},{"key":"8whkyzcj85","type":"unstyled","depth":0,"text":"가치있는 지식이 공유되는 공간을 만들어나가는데 함께해주시길 기다리고 있겠습니다 :)","styles":[],"entities":[]},{"key":"8whkyzcj88","type":"unstyled","depth":0,"text":"","styles":[],"entities":[]},{"key":"8whkyzcj89","type":"unstyled","depth":0,"text":"저희가 지향하는 답변이 무엇인지에 대해서 더 궁금하시다면 아래의 글을 읽어주시길 바랍니다.","styles":[],"entities":[]},{"key":"8whkyzcj90","type":"unstyled","depth":0,"text":"Q. 플로바는 어떤 답변을 지향하나요?","styles":[],"entities":[{"type":"link","start":0,"length":21,"data":{"url":"https://flova.kr/question/84"}}]}]',
};
