# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='followed_users',
            new_name='followers',
        ),
    ]
