# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20171128_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerbookmark',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_answers', to='contents.Answer'),
        ),
        migrations.AlterField(
            model_name='questionbookmark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_questions', to='contents.Question'),
        ),
    ]
