# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20171130_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
