export const VALIDATE_INVITE_KEY_REQUEST = 'app/InvitePage/VALIDATE_INVITE_KEY_REQUEST';
export const VALIDATE_INVITE_KEY_SUCCESS = 'app/InvitePage/VALIDATE_INVITE_KEY_SUCCESS';
export const VALIDATE_INVITE_KEY_FAILURE = 'app/InvitePage/VALIDATE_INVITE_KEY_FAILURE';
